---
- name: Set java_installer_version_string (Windows - RedHat - modern JDK)
  set_fact:
    java_installer_version_string: "{{ java_version_full_string }}"

- name: Set java_version_patch_build (Windows - RedHat - modern JDK)
  set_fact:
    java_version_patch_build: "{{ (java_version_parts['java_patch']).split('-')[1] | default('') }}"

- name: Set java_destination_version_string (Windows - RedHat - modern JDK)
  set_fact:
    java_destination_version_string: |-
      {%- if java_version_patch_build == '' %}
      {{ java_version_medium_string }}
      {%- else %}
      {{ java_version_medium_string }}-{{ java_version_patch_build }}
      {%- endif %}

- name: Set java_installer_prefix (Windows - RedHat - modern JDK)
  set_fact:
    java_installer_prefix: "java-{{ java_version_java_feature_string }}-openjdk-"

- name: Set java_installer_suffix (Windows - RedHat - modern JDK)
  set_fact:
    java_installer_suffix: ".windows.redhat.x86_64"

- name: Set java_installer_filename (Windows - RedHat - modern JDK)
  set_fact:
    java_installer_filename: "\
      {{ java_installer_prefix }}\
      {{ java_installer_version_string }}\
      {{ java_installer_suffix }}\
      {{ java_installer_ext }}"

- name: Set java_destination_dirname (Windows - RedHat - modern JDK)
  set_fact:
    java_destination_dirname: "java-{{ java_version_java_feature_string }}-\
      openjdk-{{ java_destination_version_string }}"
