---
- name: Update apt cache (Debian)
  become: true
  apt:
    update_cache: true

- name: Install java-common (Debian)
  become: true
  apt:
    pkg: java-common
    state: present

- name: Install JDK (Debian)
  become: true
  shell: "DEBIAN_FRONTEND=noninteractive dpkg -i \
    {{ java_installers_path_on_target }}/{{ java_installer_filename }}"
