---
- name: Set java_installer_ext (Windows - RedHat)
  set_fact:
    java_installer_ext: ".msi"

- name: Set java_version_style (Windows - RedHat)
  set_fact:
    java_version_style: |-
      {%- if java_vendor == 'redhat' and java_version_parts['java_feature']|int < 9 %}
      legacy
      {%- else %}
      modern
      {%- endif %}

- name: Set legacy/modern Java installer variables (Windows - RedHat)
  include_tasks: "java_installer_vars/{{ java_version_style }}.yml"
