---
- name: Set java_installer_version_string (Debian - Amazon - legacy)
  set_fact:
    java_installer_version_string: "{{ java_version_medium_string }}\
      {{ java_version_java_patch_hyphen_substring }}"

- name: Set java_destination_version_string (Debian - Amazon - legacy)
  set_fact:
    java_destination_version_string: "{{ java_version_legacy_short_string }}"

- name: Set java_installer_prefix (Debian - Amazon - legacy)
  set_fact:
    java_installer_prefix: "java-{{ java_version_legacy_short_string }}-\
      amazon-corretto-jdk_"
