---
- name: Get Java directories in java_destination_parent_path (Windows)
  win_find:
    paths: "{{ java_destination_parent_path }}"
    patterns: ["jdk*", "java*"]
    file_type: directory
    recurse: false
  register: found_dirs

# TODO: Consider a better way to do this: it's OK for clean installs, but will
#       probably cause problems for multi-java installations.
- name: Set java_path to most recent directory in java_destination_parent_path
  set_fact:
    java_path: "{{ (found_dirs.files | sort(attribute='lastwritetime') | last).path }}"
