---
- name: Get JDK directories in java_destination_parent_path (Windows)
  win_find:
    paths: "{{ java_destination_parent_path }}"
    patterns: jdk*
    file_type: directory
    recurse: false
  register: found_dirs
