---
- name: Set java_installer_suffix (Debian - Amazon)
  set_fact:
    java_installer_suffix: "_amd64"

- name: Set java_installer_ext (Debian - Amazon)
  set_fact:
    java_installer_ext: ".deb"

- name: Set java_version_style (Debian - Amazon)
  set_fact:
    java_version_style: |-
      {%- if java_vendor == 'amazon' and java_version_parts['java_feature']|int < 9 %}
      legacy
      {%- else %}
      modern
      {%- endif %}

- name: Set legacy/modern Java installer variables (Debian - Amazon)
  include_tasks: "java_installer_vars/{{ java_version_style }}.yml"

- name: Set java_installer_filename (Debian - Amazon)
  set_fact:
    java_installer_filename: "\
      {{ java_installer_prefix }}\
      {{ java_installer_version_string }}\
      {{ java_installer_suffix }}\
      {{ java_installer_ext }}"

- name: Set java_destination_dirname (Debian - Amazon)
  set_fact:
    java_destination_dirname: "java-{{ java_destination_version_string }}-\
      amazon-corretto"
  when: java_destination_dirname is not defined
