---
- name: Set java_type_string
  set_fact:
    java_type_string: "{{ java_type | default('jdk') }}"

# Build the Java version string as detailed here:
#   https://docs.oracle.com/en/java/javase/11/install/version-string-format.html
# Note: This format is also being used for older Java versions, even though
#       it does not match the old standard.  i.e. 1.8.0_202 -> 8.202

- name: Parse java_version
  set_fact:
    java_version_parts:
      java_feature: "{{ (java_version|string).split('.')[0] }}"
      java_interim: "{{ (java_version|string).split('.')[1] | default(omit) }}"
      java_update: "{{ (java_version|string).split('.')[2] | default(omit) }}"
      java_patch: "{{ (java_version|string).split('.')[3] | default(omit) }}"
      java_build: "{{ (java_version|string).split('.')[4] | default(omit) }}"

- debug:
    var: java_version_parts
    verbosity: "2"

- name: Set java_version_java_build_substring
  set_fact:
    java_version_java_build_substring: ".{{ java_version_parts['java_build'] }}"
    java_version_java_build_underscore_substring: "_{{ java_version_parts['java_build'] }}"
    java_version_java_build_hyphen_substring: "-{{ java_version_parts['java_build'] }}"
  when: java_version_parts['java_build'] is defined

- name: Set java_version_java_patch_substring
  set_fact:
    java_version_java_patch_substring: ".{{ java_version_parts['java_patch'] }}"
    java_version_java_patch_underscore_substring: "_{{ java_version_parts['java_patch'] }}"
    java_version_java_patch_hyphen_substring: "-{{ java_version_parts['java_patch'] }}"
  when: java_version_parts['java_patch'] is defined

- name: Set java_version_java_update_substring
  set_fact:
    java_version_java_update_substring: ".{{ java_version_parts['java_update'] }}"
    java_version_java_update_underscore_substring: "_{{ java_version_parts['java_update'] }}"
    java_version_java_update_b_substring: ".b{{ java_version_parts['java_update'] }}"
  when: java_version_parts['java_update'] is defined

- name: Set java_version_java_interim_substring
  set_fact:
    java_version_java_interim_substring: ".{{ java_version_parts['java_interim'] }}"
    java_version_java_interim_underscore_substring: "_{{ java_version_parts['java_interim'] }}"
  when: java_version_parts['java_interim'] is defined

- name: Set java_version_java_feature_string
  set_fact:
    java_version_java_feature_string: "{{ java_version_parts['java_feature'] }}"

- name: Set java_version_full_string
  set_fact:
    java_version_full_string: "{{ java_version_java_feature_string }}\
      {{ java_version_java_interim_substring | default('') }}\
      {{ java_version_java_update_substring | default('') }}\
      {{ java_version_java_patch_substring | default('') }}\
      {{ java_version_java_build_substring | default('') }}"

- name: Set java_version_long_string
  set_fact:
    java_version_long_string: "{{ java_version_java_feature_string }}\
      {{ java_version_java_interim_substring | default('') }}\
      {{ java_version_java_update_substring | default('') }}\
      {{ java_version_java_patch_substring | default('') }}"

- name: Set java_version_medium_string
  set_fact:
    java_version_medium_string: "{{ java_version_java_feature_string }}\
      {{ java_version_java_interim_substring | default('') }}\
      {{ java_version_java_update_substring | default('') }}"

- name: Set java_version_short_string
  set_fact:
    java_version_short_string: "{{ java_version_java_feature_string }}\
      {{ java_version_java_interim_substring | default('') }}"

- debug:
    var: java_version_full_string
    verbosity: "2"

- debug:
    var: java_version_long_string
    verbosity: "2"

- debug:
    var: java_version_medium_string
    verbosity: "2"

- debug:
    var: java_version_short_string
    verbosity: "2"

- name: Set java_version_legacy_full_string
  set_fact:
    java_version_legacy_full_string:
      "1.{{ java_version_java_feature_string }}.0\
      {{ java_version_java_interim_underscore_substring | default('') }}\
      {{ java_version_java_update_b_substring | default('') }}\
      {{ java_version_java_patch_substring | default('') }}\
      {{ java_version_java_build_substring | default('') }}"

- name: Set java_version_legacy_medium_string
  set_fact:
    java_version_legacy_medium_string:
      "1.{{ java_version_java_feature_string }}.0\
      {{ java_version_java_interim_underscore_substring | default('') }}"

- name: Set java_version_legacy_short_string
  set_fact:
    java_version_legacy_short_string: "1.{{ java_version_java_feature_string }}.0"

- debug:
    var: java_version_legacy_full_string
    verbosity: "2"

- debug:
    var: java_version_legacy_medium_string
    verbosity: "2"

- debug:
    var: java_version_legacy_short_string
    verbosity: "2"
