---
# Build the Java version string as detailed here:
#   https://docs.oracle.com/en/java/javase/11/install/version-string-format.html
# Note: This format is also being used for older Java versions, even though
#       it does not match the old standard.  i.e. 1.8.0_202 -> 8.202

- name: Parse java_version
  set_fact:
    java_version_parts:
      feature: "{{ (java_version|string).split('.')[0] }}"
      interim: "{{ (java_version|string).split('.')[1] | default('0') }}"
      update: "{{ (java_version|string).split('.')[2] | default('0') }}"
      patch: "{{ (java_version|string).split('.')[3] | default('0') }}"

- name: Set java_version_string
  set_fact:
    java_version_string: |-
      {%- set version_subparts = ['patch', 'update'] -%}
      {%- set version = { 'string': '' } -%}
      {%- for part in version_subparts %}
      {%-   if java_version_parts[part]|int != 0 or version.string != '' %}
      {%-     if version.update({'string':'.' + java_version_parts[part]|string + version.string}) %}{%- endif %}
      {%-   endif %}
      {%- endfor %}
      {%- if java_version_parts['interim'] != '' %}
      {%-   if version.update({'string':'.' + java_version_parts['interim']|string + version.string}) %}{%- endif %}
      {%- endif %}
      {%- if version.update({'string':java_version_parts['feature']|string + version.string}) %}{%- endif %}
      {{ version.string }}

- name: Set java_version_short_string
  set_fact:
    java_version_short_string: |-
      {%- set version = { 'string': '' } -%}
      {%- if java_version_parts['interim'] != '' %}
      {%-   if version.update({'string':'.' + java_version_parts['interim']|string + version.string}) %}{%- endif %}
      {%- endif %}
      {%- if version.update({'string':java_version_parts['feature']|string + version.string}) %}{%- endif %}
      {{ version.string }}

- name: Set java_version_legacy_string
  set_fact:
    java_version_legacy_string: |-
      {%- set version = { 'string': '' } -%}
      {%- if java_version_parts['patch']|int != 0 or version.string != '' %}
      {%-   if version.update({'string':'.' + java_version_parts['patch']|string + version.string}) %}{%- endif %}
      {%- endif %}
      {%- if java_version_parts['update']|int != 0 or version.string != '' %}
      {%-   if version.update({'string':'.b' + java_version_parts['update']|string + version.string}) %}{%- endif %}
      {%- endif %}
      {%- if java_version_parts['interim'] != '' or version.string != '' %}
      {%-   if version.update({'string':'_' + java_version_parts['interim']|string + version.string}) %}{%- endif %}
      {%- endif %}
      {%- if version.update({'string':'1.' + java_version_parts['feature']|string + '.0' + version.string}) %}{%- endif %}
      {{ version.string }}

- name: Set java_version_legacy_medium_string
  set_fact:
    java_version_legacy_medium_string: |-
      {%- set version = { 'string': '' } -%}
      {%- if java_version_parts['interim'] != '' or version.string != '' %}
      {%-   if version.update({'string':'_' + java_version_parts['interim']|string + version.string}) %}{%- endif %}
      {%- endif %}
      {%- if version.update({'string':'1.' + java_version_parts['feature']|string + '.0' + version.string}) %}{%- endif %}
      {{ version.string }}

- name: Set java_version_legacy_medium_dot_string
  set_fact:
    java_version_legacy_medium_dot_string: |-
      {%- set version = { 'string': '' } -%}
      {%- if java_version_parts['interim'] != '' or version.string != '' %}
      {%-   if version.update({'string':'.' + java_version_parts['interim']|string + version.string}) %}{%- endif %}
      {%- endif %}
      {%- if version.update({'string':'1.' + java_version_parts['feature']|string + '.0' + version.string}) %}{%- endif %}
      {{ version.string }}

- name: Set java_version_legacy_short_string
  set_fact:
    java_version_legacy_short_string: "1.{{ java_version_parts['feature']|string }}.0"

- name: Set java_type_string
  set_fact:
    java_type_string: "{{ java_type | default('jdk') }}"

- name: DEBUG - java_version_string
  debug:
    var: java_version_string

- name: DEBUG - java_version_short_string
  debug:
    var: java_version_short_string

- name: DEBUG - java_version_legacy_string
  debug:
    var: java_version_legacy_string

- name: DEBUG - java_version_legacy_medium_string
  debug:
    var: java_version_legacy_medium_string

- name: DEBUG - java_version_legacy_medium_dot_string
  debug:
    var: java_version_legacy_medium_dot_string

- name: DEBUG - java_version_legacy_short_string
  debug:
    var: java_version_legacy_short_string
